# select the mode to run in, either as "plugin" or "verifier"
mode: verifier

# when "plugin" mode is selected, choose which package to run: "dca", "payroll", etc.
plugin_type: ""

# plugin package specific configuration
plugin_package:
  payroll:
    rpc_url: http://127.0.0.1:8545
  dca:
    # use private mempool https://rpc.mevblocker.io
    rpc_url: http://127.0.0.1:8545
    uniswap:
      v2_router: 0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D
      deadline: 5 # minutes

# "plugin" or "verifier" server configuration
plugin:
  host: localhost
  port: 8081

# relevant when mode is "plugin", each plugin has to communicate with its verifier
verifier:
  host: localhost
  port: 8080

vaults_file_path: /tmp/plugin/vaults
jwt_secret: myjwtsecretphrase

database:
  dsn: postgres://myuser:mypassword@localhost:5432/vultisig-verifier?sslmode=disable

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0

block_storage:
  type: s3
  endpoint: http://localhost:9000
  bucket: vultisig-verifier
  access_key: minioadmin
  secret: minioadmin
  region: us-east-1
  host: http://localhost:9000
  force_path_style: true
  disable_ssl: true

relay:
  server: https://api.vultisig.com/router

email_server:
  api_key: key-1234567890

datadog:
  host: localhost
  port: 8125
